config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  resources :projects, only: [:new, :create, :show, :update] do
    resources :project_results, only: [:show]
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  include AASM
  serialize :field_signature, JSON

  belongs_to :user
  belongs_to :target_user, class_name: "User"

  has_many :source_rows, -> { source }, class_name: "ProjectRow", dependent: :delete_all
  has_many :target_rows, -> { target }, class_name: "ProjectRow", dependent: :delete_all

  has_many :results, class_name: "ProjectResult", dependent: :delete_all

  validates :user, presence: true
  validates :field_signature, presence: true, :if => :configured?
  validates :target_user, presence: true, :if => :target_selected?

  before_create :set_slug

  aasm column: :state, whiny_transitions: false do
    state :new, initial: true
    state :configured
    state :source_uploaded
    state :target_selected
    state :target_uploaded
    state :completed

    event :configure do
      before do |*args|
        set_configs(*args)
      end

      transitions from: :new, to: :configured
    end

    event :finalize_source do
      transitions from: :configured, to: :source_uploaded
    end

    event :select_target do
      before do |*args|
        set_target(*args)
      end

      transitions from: :source_uploaded, to: :target_selected
    end

    event :finalize_target do
      after do
        ProjectDiffJob.perform_later(self)
      end
      transitions from: :target_selected, to: :target_uploaded
    end

    event :complete do
      transitions from: :target_uploaded, to: :completed
    end
  end

  #convenience method to keep the source/target semantics consistent
  def source_user
    user
  end
  #we override to_param to use slug for our restful controller actions
  def to_param
    slug
  end

  def target_rows_size
    rows_size(:target)
  end

  def source_rows_size
    rows_size(:source)
  end  

  def humanized_fields
    return [] unless field_signature.respond_to?(:map)
    field_signature.map(&:humanize)
  end

  def result_files
    results.map{|r| [r.result_type,r.id]}.to_h
  end

  private
    def rows_size(type)
      send("#{type}_rows").size
    end

    def set_configs(configs)
      if configs[:field_signature]
        self.field_signature = configs[:field_signature]
      end
    end

    def set_target(target)
      self.target_user = target
    end

    def set_slug
      self.slug = SecureRandom.hex
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def new
    @project_form = ProjectForm.new
  end

  def show
    @project = Project.find_by_slug(params[:id])
    @project.decorate
    respond_to do |format|
      if @project
        @project = @project.decorate
        format.html #show.html.erb
        format.json do
          render status: :ok, json: @project.to_hash
        end
      else
        format.html do
          flash[:danger] = "Could not find that project"
          redirect_to :back and return
        end

        format.json do
          render status: 404, json: { errors: ["project not found"] }
        end
      end
    end
  end

  def create
    @project_form = ProjectForm.new(project_form_params)

    if @project = @project_form.submit
      redirect_to @project
    else
      flash.now[@project_form.message_level] = @project_form.message
      render "new"
    end
  end

  def update
    @project = Project.find_by_slug(params[:id])

    @project_updater = ProjectUpdater.new(@project)

    respond_to do |format|
      if @project_updater.call(project_update_op, project_update_args)
        format.json do
          render status: :ok, json: @project_updater.return_data
        end
      else
        format.json do
          render status: :unprocessable_entity, json: {errors: @project_updater.errors}
        end
      end
    end
  end

  private
    def project_form_params
      params
        .require(:project_form)
        .permit(ProjectForm.permitted_attributes)
    end

    def project_update_op
      params[:op]
    end

    def project_update_args
      params[:args]
    end
end

app/views/projects/_project_complete.html.erb
<p>The project is complete</p>
<%= render "project_results" %>

app/views/projects/_results_checker.html.erb
<p>This is the results checker.</p>

app/views/projects/_results_presenter.html.erb
<p>This is the results presenter.</p>
<div data-bind="visible: has_file('overlap')">
  <p>Here is the overlap file: <a data-bind="attr: {href: path_to('overlap')}">csv</a></p>
</div> 
<div data-bind="visible: has_file('source_uniques')">
  <p>Here is the source_uniques file: <a data-bind="attr: {href: path_to('source_uniques')}">csv</a></p>
</div> 
<div data-bind="visible: has_file('target_uniques')">
  <p>Here is the target_uniques file: <a data-bind="attr: {href: path_to('target_uniques')}">csv</a></p>
</div> 
<div data-bind="visible: has_file('source_duplicates')">
  <p>Here is the source_duplicates file: <a data-bind="attr: {href: path_to('source_duplicates')}">csv</a></p>
</div> 
<div data-bind="visible: has_file('target_duplicates')">
  <p>Here is the target_duplicates file: <a data-bind="attr: {href: path_to('target_duplicates')}">csv</a></p>
</div> 

app/views/projects/_source_uploader.html.erb
<div>
  <input type="file" accept=".csv" data-bind="file: file">
  <button data-bind="visible: file, click: readSourceHeader">Looky loo</button>
</div>
<div data-bind="with: header">
  <table>
    <thead>
      <tr data-bind="foreach: header().row()">
        <th>
          <div data-bind="text: $data"></div>
          <div>
            <label>Unique id</label>
            <input type="radio" name="unique_id" data-bind="checkedValue: $index, checked: $parents[1].unique_id_idx, click: function(){ $parents[1].clear_diff_fields($index()); return true;}"/>
          </div>
          <div>
            <label>Use to diff</label>
            <input type="checkbox" data-bind="checkedValue: [$index(),$data], checked: $parents[1].diff_fields, disable: $parents[1].unique_id_idx() === $index()" />
          </div>
        </th>
      </tr>
    </thead>
    <tbody data-bind="foreach: rows()">
      <tr data-bind="foreach: $data.row()">
        <td data-bind="text: $data"></td>
      </tr>
    </tbody>
  </table>
</div>
<button data-bind="click: submit">Submit</button>
<div data-bind="visible: showRowsUploaded">
  Uploaded: <span data-bind="text: parent.source_rows_uploaded"></span>
</div>

app/views/projects/_target_selector.html.erb
<div>
  <p>You uploaded <span data-bind="text: parent.source_rows_uploaded"></span> rows</p>
  <p>Who do you want to compare lists with?</p>
  <input type="email" data-bind="value: target_email" />
  <button data-bind="click: submit">Submit</button>
</div>

app/views/projects/_target_uploader.html.erb
<div>
  <p>Time to upload the target data now</p>
  <p>Your contact uploaded <span data-bind="text: parent.source_rows_uploaded"></span> rows with the fields:</p>
  <ul data-bind="foreach: parent.field_signature">
    <li data-bind="text: $data"></li>
  </ul>
</div>
<div>
  <input type="file" accept=".csv" data-bind="file: file">
  <button data-bind="visible: file, click: readHeader">Looky loo</button>
</div>
<div data-bind="with: header">
  <table>
    <thead>
      <tr data-bind="foreach: header().row()">
        <th>
          <div data-bind="text: $data"></div>
          <div>
            <label>Unique id</label>
            <input type="radio" name="unique_id" data-bind="checkedValue: $index, checked: $parents[1].unique_id_idx"/>
          </div>
          <div data-bind="foreach: $parents[1].parent.field_signature">
            <div>
              <label data-bind="text: $data"></label>
              <input type="radio" data-bind="checkedValue: $parentContext.$index, checked: $parents[2].field_for($index)" />
            </div>
          </div>
        </th>
      </tr>
    </thead>
    <tbody data-bind="foreach: rows()">
      <tr data-bind="foreach: $data.row()">
        <td data-bind="text: $data"></td>
      </tr>
    </tbody>
  </table>
</div>
<button data-bind="click: submit">Submit</button>
<div data-bind="visible: showRowsUploaded">
  Uploaded: <span data-bind="text: parent.target_rows_uploaded"></span>
</div>

app/views/projects/_update_browser.html.erb
<div>
  What's The Diff cannot be used with this browser, please update to....
</div>

app/views/projects/new.html.erb
<h1>Create a new project</h1>

<%= form_for @project_form, url: projects_path do |f| %>
  <%= f.hidden_field :collect_info, value: "yes" %>
  <%= f.text_field :first_name, placeholder: "First Name" %>
  <%= f.text_field :last_name, placeholder: "Last Name" %>
  <%= f.email_field :email, placeholder: "Email" %>
  <%= f.text_field :company, placeholder: "Company" %>
  <%= f.submit %>
<% end %>

app/views/projects/show.html.erb
<div id='app' style="display:none" data-bind="visible: $data">
  <div data-bind="visible: hasFileApi()">
    <div data-bind="with: state_app">
      <div data-bind="template: {name: name, data: $data}">
      </div>
    </div>
  </div>
  <div data-bind="visible: !hasFileApi()">
    <%= render 'update_browser' %>
  </div>
</div>

<% content_for :foot do %> 
  <%= javascript_include_tag "lib/knockout-min.js" %>
  <%= javascript_include_tag "lib/linereader.js" %>
  <%= javascript_include_tag "lib/csv.js" %>
  <%= javascript_include_tag "lib/md5.js" %>
  <%= javascript_include_tag "knockout/ko-file.js" %>
  <%= javascript_include_tag "knockout/app.js" %>
  <%= javascript_include_tag "knockout/uploader.js" %>
  <% @project.templates.each do |template| %>
    <%= javascript_include_tag "knockout/#{template}.js" %>
    <script type="text/html" id="<%= template %>">
      <%= render template %>
    </script>
  <% end %>
  <script>
    ko.applyBindings(new App(<%= @project.knockout %>), $('.app')[0])
  </script>
<% end %>